### PR TITLE
Make room a unique field to deal with duplicate room bug

### LINKED ISSUE #170: [PE-D] Multiple users with different names can be assigned to the same room
Command:
`add n/Sherman Ngg r/A111 p/1234 e/emaiL@sample.com v/T f/aa cd/01-05-2022`
then 
`edit 7 r/A111`
then
`edit 6 r/A111`

Result:
3 residents in the same room.

Remarks:
There is not explicit mention if this field needs to be unique. Might be good to include in UG if the rooms in the halls allow for more than one user to stay (double-rooms or triple-rooms). Might want to consider making this field unqiue

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: shermannws/ped#3

### LINKED ISSUE #197: [PE-D] `include` command does not add all the residents of a room to an event
Replicating error:
- There is originally 3 residents in the same room.

- Execute `include 2 r/A111` 

Outcome:
- Only one of the three residents is being added to the event.

Remarks:
This can be detrimental since the intention may be to include another resident or all 3 residents. More refinement into this function might be needed in order to be bug-free. All the best!

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: shermannws/ped#10

### LINKED ISSUE #198: [PE-D] Existing resident in the application cannot be included in an event
Command Executed:
- Note that there is already a user "Sherman Ng" in the application.

- Under the "events" tab, `include 3 r/Sherman Ng` is being executed.

Outcome:
Upon pressing "Enter", there is no response and feedback from the application. The command cannot be executed and there is no response or error thrown.

Further remarks:
Upon further testing, `include 3 r/Bernice Yu` works and successfully adds Bernice Yu to the event at index 3. The underlying fault might be attributed to "Sherman Ng" having the same room number as "Roy Balakrishnan".  

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: shermannws/ped#11

### LINKED ISSUE #221: [PE-D] Bug when adding two students with the same room number to an event using the include command
First created two students, john and Joh, with the same room number.

Next try to add both students by calling the `include` command with the room name, but only one of them is added. Tried to use the same command again but is unable to add the other student. Can only add both students with the  same room number by passing their names in the `include` command.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: nguyiyang/ped#9

### LINKED ISSUE #222: [PE-D] Bug when removing two students from an event with the same room number using exclude command
First created two students, john and Joh, with the same room number using the `include` command and adding students by their NAMES(not room number - see issue#9 for related bug). Now we have two students in an event with the same room number.

Next try to remove both students by calling the `exclude` command with the room name, but only one of them is removed. Tried to use the same command again but is unable to remove the other student with the error displayed as such in the above image. Can only remove both students with the same room number by passing their names in the `exclude` command.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: nguyiyang/ped#10

### LINKED ISSUE #224: [PE-D] Adding two students with the same room number to an event using add command
Steps:
First create two students with the same room number(a100).
Then using the `add` command, add student to event using the room name as a parameter.
Result: 
Only the first student matching that room number is added.

Not sure whether it is intended for two students to have the same room number! If so, it would likely cause errors when adding students to events by room number.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: nguyiyang/ped#11

### PR DESCRIPTION
**Pull request by gordonlzy**
Closes #170
Closes #197
Closes #198
Closes #221
Closes #222 
Closes #224

### CODE REVIEW

File: src/main/java/safeforhall/logic/commands/add/AddPersonCommand.java [hunk 1]
```diff
@@ -39,7 +39,7 @@
             + CliSyntax.PREFIX_COLLECTIONDATE + "23-10-2021 ";
 
     public static final String MESSAGE_SUCCESS = "New resident added: %1$s";
-    public static final String MESSAGE_DUPLICATE_PERSON = "This resident already exists in the address book";
+    public static final String MESSAGE_DUPLICATE_PERSON = "This resident or room already exist in the address book";
```
Comment (VimuthM) [inline src/main/java/safeforhall/logic/commands/add/AddPersonCommand.java:42]:
```suggestion
    public static final String MESSAGE_DUPLICATE_PERSON = "This resident or room already exists in the address book";
```

File: src/main/java/safeforhall/logic/commands/edit/EditPersonCommand.java [hunk 2]
```diff
@@ -52,7 +52,7 @@
 
     public static final String MESSAGE_EDIT_PERSON_SUCCESS = "Edited Residents: \n%1$s";
     public static final String MESSAGE_NOT_EDITED = "At least one field to edit must be provided.";
-    public static final String MESSAGE_DUPLICATE_PERSON = "This resident already exists in the address book.";
+    public static final String MESSAGE_DUPLICATE_PERSON = "This resident or room already exist in the address book.";
```
Comment (VimuthM) [inline src/main/java/safeforhall/logic/commands/edit/EditPersonCommand.java:55]:
```suggestion
    public static final String MESSAGE_DUPLICATE_PERSON = "This resident or room already exists in the address book.";
```

**Review by VimuthM — CHANGES_REQUESTED** [review]
